### ISSUE TITLE
线性回归的初试

### ISSUE THREAD

**Issue by LIUHaohui** [huaxz1986/git_book#2]
您好，我在使用您的，linear_regression.py 时遇到了：
Traceback (most recent call last):
  File "/Users/liuhaohui/Desktop/4th/py/Muster 2.py", line 18, in <module>
    X_train,X_test,y_train,y_test=load_data() 
  File "/Users/liuhaohui/Desktop/4th/py/Muster 2.py", line 7, in load_data
    return cross_validation.train_test_split(datasets.data,diabetes.target,
AttributeError: 'module' object has no attribute 'data'
问题，请问是什么原因引起的'module' object has no attribute 'data'？
谢谢

**Comment by zhzhx0318** [comment]
one bug in code.

chapters/Linear/linear_regression.py
line22
change：
return cross_validation.train_test_split(datasets.data,diabetes.target,
to：
return cross_validation.train_test_split(diabetes.data,diabetes.target,

more details please see Pull requests

**Comment by ghost** [comment]
坑，刚运行第一个程序就不对，作者从哪抄来的

**Comment by ghost** [comment]
load_data函数里数据经过train_test_split 返回值明明是个列表，光明正大的写个元祖？？？？
难怪这本书放在图书馆里没人借，太坑了。
作者不用心不仅是坑自己 还是坑别人
![default](https://user-images.githubusercontent.com/24308993/29904467-850cc6b8-8e3b-11e7-9992-ecc3672223dd.png)

**Comment by xucongyong** [comment]
只有初中数学水平咋补？

**Comment by buchixiaoyaoran** [comment]
书上代码没有错误，给的源码估计是手误打错了，应该是diabetes.data,，不是datasets.data，还有一点，由于现在官方调整，cross_validation被弃用，改到model_selection里面了，所以代码应该改成如下：
# -*- coding: utf-8 -*-
"""
    广义线性模型
    ~~~~~~~~~~~~~~~~~~~~~~~~~~

    LinearRegression

    :copyright: (c) 2016 by the huaxz1986.
    :license: lgpl-3.0, see LICENSE for more details.
"""
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split

def load_data():
    '''
    加载用于回归问题的数据集

    :return: 一个元组，用于回归问题。元组元素依次为：训练样本集、测试样本集、训练样本集对应的值、测试样本集对应的值
    '''
    diabetes = datasets.load_diabetes()#使用 scikit-learn 自带的一个糖尿病病人的数据集
    return train_test_split(diabetes.data,diabetes.target,
		test_size=0.25,random_state=0) # 拆分成训练集和测试集，测试集大小为原始数据集大小的 1/4
def test_LinearRegression(*data):
    '''
    测试 LinearRegression 的用法

    :param data: 可变参数。它是一个元组，这里要求其元素依次为：训练样本集、测试样本集、训练样本的值、测试样本的值
    :return: None
    '''
    X_train,X_test,y_train,y_test=data
    regr = linear_model.LinearRegression()
    regr.fit(X_train, y_train)
    print('Coefficients:%s, intercept %.2f'%(regr.coef_,regr.intercept_))
    print("Residual sum of squares: %.2f"% np.mean((regr.predict(X_test) - y_test) ** 2))
    print('Score: %.2f' % regr.score(X_test, y_test))
if __name__=='__main__':
    X_train,X_test,y_train,y_test=load_data() # 产生用于回归问题的数据集
    test_LinearRegression(X_train,X_test,y_train,y_test) # 调用 test_LinearRegression

**Comment by buchixiaoyaoran** [comment]
书上的代码没有错误，应该是diabetes.data而不是datasets.data，估计是手误打错了，然后由于3.1版本官方调整，cross_validation被弃用，合并到model_selection里面了，所以代码有所改动，如下：

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
def load_data():
    diabetes = datasets.load_diabetes()#使用 scikit-learn 自带的一个糖尿病病人的数据集
    return train_test_split(diabetes.data,diabetes.target,test_size=0.25,random_state=0) # 拆分成训练集和测试集，测试集大小为原始数据集大小的 1/4

def test_LinearRegression(*data):
    X_train,X_test,y_train,y_test=data
    regr = linear_model.LinearRegression()
    regr.fit(X_train, y_train)
    print('Coefficients:%s, intercept %.2f'%(regr.coef_,regr.intercept_))
    print("Residual sum of squares: %.2f"% np.mean((regr.predict(X_test) - y_test) ** 2))
    print('Score: %.2f' % regr.score(X_test, y_test))

if __name__=='__main__':
    X_train,X_test,y_train,y_test=load_data() # 产生用于回归问题的数据集
    test_LinearRegression(X_train,X_test,y_train,y_test) # 调用 test_LinearRegression

**Comment by duanshengliu** [comment]
书上的代码没有错误，应该是diabetes.data而不是datasets.data，估计是手误打错了，然后由于3.1版本官方调整，cross_validation被弃用，合并到model_selection里面了，所以代码有所改动，如下：
[linear_regression.txt](https://github.com/huaxz1986/git_book/files/2670582/linear_regression.txt)
运行结果和书上一样，如下：
Coefficients:[ -43.26774487 -208.67053951  593.39797213  302.89814903 -560.27689824
  261.47657106   -8.83343952  135.93715156  703.22658427   28.34844354], intercept 153.07
Residual sum of squares: 3180.20
Score: 0.36

**Comment by huaxz1986** [comment]
已经修复这个问题
