### ISSUE TITLE
书上第85页上有个地方求解

### ISSUE THREAD

**Issue by HuXiLiFeng** [huaxz1986/git_book#3]
样本点Xi在新坐标系和原始坐标系上的表示是不一样的，但是书上就直接来了个两个相等，这是为什么啊

**Comment by huaxz1986** [comment]
同一个向量，在两个坐标系中的坐标确实不同。但是，如果把基向量考虑在内，则二者相同。它描述了一个事实：一个向量，无论在哪个坐标系中，它本身是不会发生变化的。
